#ifndef _MYSPI_H
#define _MYSPI_H
#include "sys.h"

#define D0(n)         (n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_14,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_14,GPIO_PIN_RESET)) 
#define D1(n)         (n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_15,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_15,GPIO_PIN_RESET))  
#define D2(n)         (n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_0,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_0,GPIO_PIN_RESET))  
#define D3(n)         (n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_1,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_1,GPIO_PIN_RESET))   

#define D4(n)         (n?HAL_GPIO_WritePin(GPIOE,GPIO_PIN_7,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOE,GPIO_PIN_7,GPIO_PIN_RESET))  
#define D5(n)         (n?HAL_GPIO_WritePin(GPIOE,GPIO_PIN_8,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOE,GPIO_PIN_8,GPIO_PIN_RESET))  
#define D6(n)         (n?HAL_GPIO_WritePin(GPIOE,GPIO_PIN_9,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOE,GPIO_PIN_9,GPIO_PIN_RESET))  
#define D7(n)         (n?HAL_GPIO_WritePin(GPIOE,GPIO_PIN_10,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOE,GPIO_PIN_10,GPIO_PIN_RESET))  
#define D8(n)         (n?HAL_GPIO_WritePin(GPIOE,GPIO_PIN_11,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOE,GPIO_PIN_11,GPIO_PIN_RESET))  
#define D9(n)         (n?HAL_GPIO_WritePin(GPIOE,GPIO_PIN_12,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOE,GPIO_PIN_12,GPIO_PIN_RESET))  
#define D10(n)        (n?HAL_GPIO_WritePin(GPIOE,GPIO_PIN_13,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOE,GPIO_PIN_13,GPIO_PIN_RESET))  
#define D11(n)        (n?HAL_GPIO_WritePin(GPIOE,GPIO_PIN_14,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOE,GPIO_PIN_14,GPIO_PIN_RESET))  
#define D12(n)        (n?HAL_GPIO_WritePin(GPIOE,GPIO_PIN_15,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOE,GPIO_PIN_15,GPIO_PIN_RESET))  

#define D13(n)        (n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_8,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_8,GPIO_PIN_RESET))    
#define D14(n)        (n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_9,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_9,GPIO_PIN_RESET)) 
#define D15(n)        (n?HAL_GPIO_WritePin(GPIOD,GPIO_PIN_10,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOD,GPIO_PIN_10,GPIO_PIN_RESET)) 

#define D16(n)        (n?HAL_GPIO_WritePin(GPIOH,GPIO_PIN_8,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOH,GPIO_PIN_8,GPIO_PIN_RESET))
#define D17(n)        (n?HAL_GPIO_WritePin(GPIOH,GPIO_PIN_9,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOH,GPIO_PIN_9,GPIO_PIN_RESET))
#define D18(n)        (n?HAL_GPIO_WritePin(GPIOH,GPIO_PIN_10,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOH,GPIO_PIN_10,GPIO_PIN_RESET))
#define D19(n)        (n?HAL_GPIO_WritePin(GPIOH,GPIO_PIN_11,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOH,GPIO_PIN_11,GPIO_PIN_RESET))
#define D20(n)        (n?HAL_GPIO_WritePin(GPIOH,GPIO_PIN_12,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOH,GPIO_PIN_12,GPIO_PIN_RESET))
#define D21(n)        (n?HAL_GPIO_WritePin(GPIOH,GPIO_PIN_13,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOH,GPIO_PIN_13,GPIO_PIN_RESET))
#define D22(n)        (n?HAL_GPIO_WritePin(GPIOH,GPIO_PIN_14,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOH,GPIO_PIN_14,GPIO_PIN_RESET))
#define D23(n)        (n?HAL_GPIO_WritePin(GPIOH,GPIO_PIN_15,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOH,GPIO_PIN_15,GPIO_PIN_RESET))

#define D24(n)        (n?HAL_GPIO_WritePin(GPIOI,GPIO_PIN_0,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOI,GPIO_PIN_0,GPIO_PIN_RESET)) 
#define D25(n)        (n?HAL_GPIO_WritePin(GPIOI,GPIO_PIN_1,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOI,GPIO_PIN_1,GPIO_PIN_RESET)) 
#define D26(n)        (n?HAL_GPIO_WritePin(GPIOI,GPIO_PIN_2,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOI,GPIO_PIN_2,GPIO_PIN_RESET)) 
#define D27(n)        (n?HAL_GPIO_WritePin(GPIOI,GPIO_PIN_3,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOI,GPIO_PIN_3,GPIO_PIN_RESET)) 
#define D28(n)        (n?HAL_GPIO_WritePin(GPIOI,GPIO_PIN_6,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOI,GPIO_PIN_6,GPIO_PIN_RESET)) 
#define D29(n)        (n?HAL_GPIO_WritePin(GPIOI,GPIO_PIN_7,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOI,GPIO_PIN_7,GPIO_PIN_RESET)) 
#define D30(n)        (n?HAL_GPIO_WritePin(GPIOI,GPIO_PIN_9,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOI,GPIO_PIN_9,GPIO_PIN_RESET)) 
#define D31(n)        (n?HAL_GPIO_WritePin(GPIOI,GPIO_PIN_10,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOI,GPIO_PIN_10,GPIO_PIN_RESET)) 

#define FIFO(n)		 (n?HAL_GPIO_WritePin(GPIOF,GPIO_PIN_1,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOF,GPIO_PIN_1,GPIO_PIN_RESET))
#define EN_DA0(n)				(n?HAL_GPIO_WritePin(GPIOF,GPIO_PIN_2,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOF,GPIO_PIN_2,GPIO_PIN_RESET))
#define ENABLE(n) 		(n?HAL_GPIO_WritePin(GPIOF,GPIO_PIN_4,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOF,GPIO_PIN_4,GPIO_PIN_RESET))
#define SCLK(n) 		(n?HAL_GPIO_WritePin(GPIOF,GPIO_PIN_3,GPIO_PIN_SET):HAL_GPIO_WritePin(GPIOF,GPIO_PIN_3,GPIO_PIN_RESET))
void SPI_Init(void);

#endif




