#include "myspi.h"
#include "delay.h"

void SPI_Init(void)
{
	//DATA数据脚
	GPIO_InitTypeDef GPIO_Initure;
  __HAL_RCC_GPIOD_CLK_ENABLE();			//开启GPIOD时钟
  __HAL_RCC_GPIOE_CLK_ENABLE();			//开启GPIOE时钟
  __HAL_RCC_GPIOH_CLK_ENABLE();			//开启GPIOH时钟
	__HAL_RCC_GPIOI_CLK_ENABLE();			//开启GPIOI时钟
	
  GPIO_Initure.Pin=GPIO_PIN_14|GPIO_PIN_15|GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10; //D0,D1,D2,D3,D13,D14,D15
  GPIO_Initure.Mode=GPIO_MODE_INPUT;  //输入
  GPIO_Initure.Pull=GPIO_PULLUP;          //上拉
  GPIO_Initure.Speed=GPIO_SPEED_HIGH;     //高速
  HAL_GPIO_Init(GPIOD,&GPIO_Initure);
	
	GPIO_Initure.Pin=GPIO_PIN_7|GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15; //D4,D5,D6,D7,D8,D9,D10,D11,D12
	HAL_GPIO_Init(GPIOE,&GPIO_Initure);
	
	GPIO_Initure.Pin=GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10|GPIO_PIN_11|GPIO_PIN_12|GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15; //D16,D17,D18,D19,D20,D21,D22,D23
  HAL_GPIO_Init(GPIOH,&GPIO_Initure);
	
	GPIO_Initure.Pin=GPIO_PIN_0|GPIO_PIN_1|GPIO_PIN_2|GPIO_PIN_3|GPIO_PIN_6|GPIO_PIN_7|GPIO_PIN_9|GPIO_PIN_10; //D24,D25,D26,D27,D28,D29,D30,D31
	HAL_GPIO_Init(GPIOI,&GPIO_Initure);
	
  

}






